// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-nH7AREOttQGMdNeO-K5fZQCDEwaVsw',
    appId: '1:30359020028:web:f2d3bc110b687493a99279',
    messagingSenderId: '30359020028',
    projectId: 'secatask',
    authDomain: 'secatask.firebaseapp.com',
    storageBucket: 'secatask.firebasestorage.app',
    measurementId: 'G-2J1LMXZ4L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk5O_py8Bj6po_yolCRE3CZ79g402wIGE',
    appId: '1:30359020028:android:cf77d4e04bf4d724a99279',
    messagingSenderId: '30359020028',
    projectId: 'secatask',
    storageBucket: 'secatask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1RwSmvlfFCMYrY0EcGiZ6eGQzPf2CrH8',
    appId: '1:30359020028:ios:24697f63fa492e2aa99279',
    messagingSenderId: '30359020028',
    projectId: 'secatask',
    storageBucket: 'secatask.firebasestorage.app',
    iosBundleId: 'com.example.secatask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1RwSmvlfFCMYrY0EcGiZ6eGQzPf2CrH8',
    appId: '1:30359020028:ios:24697f63fa492e2aa99279',
    messagingSenderId: '30359020028',
    projectId: 'secatask',
    storageBucket: 'secatask.firebasestorage.app',
    iosBundleId: 'com.example.secatask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9-nH7AREOttQGMdNeO-K5fZQCDEwaVsw',
    appId: '1:30359020028:web:c260d838528dae18a99279',
    messagingSenderId: '30359020028',
    projectId: 'secatask',
    authDomain: 'secatask.firebaseapp.com',
    storageBucket: 'secatask.firebasestorage.app',
    measurementId: 'G-N7Z8KRTYF9',
  );
}
